# Acronime specifice Capitolului 1 ATS (Evaluarea prognozelor, reguli de scor și combinarea prognozelor)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
# OVERRIDE_CH (optional): acronim -> tuplu, sens diferit doar in acest capitol.
EXTRA = {
    'PIT': ('Probability Integral Transform', 'en', 'transformarea integrală de probabilitate', None),
    'GW': ('Giacomini–White (test of conditional predictive ability)', 'en', 'testul Giacomini–White de capacitate predictivă condiționată', None),
    'MZ': ('Mincer–Zarnowitz (regression)', 'en', 'regresia Mincer–Zarnowitz', None),
    'RC': ("White's Reality Check (for data snooping)", 'en', 'testul Reality Check al lui White (pentru data snooping)', None),
    'MCS': ('Model Confidence Set', 'en', 'mulțimea de încredere a modelelor', None),
    'CRPS': ('Continuous Ranked Probability Score', 'en', 'scorul probabilistic continuu', None),
    'CPIAUCSL': ('Consumer Price Index for All Urban Consumers (FRED series code)', 'en', 'indicele prețurilor de consum pentru toți consumatorii urbani (codul seriei în FRED)', None),
    'UNRATE': ('Unemployment Rate (FRED series code)', 'en', 'rata șomajului (codul seriei în FRED)', None),
    'EA': ('Euro Area', 'en', 'zona euro', None),
    'ZE': ('Zona euro', 'ro', None, 'euro area'),
    'ISE': ('(Fraunhofer) Institute for Solar Energy Systems', 'en', 'Institutul Fraunhofer pentru sisteme de energie solară', None),
    'ENTSO-E': ('European Network of Transmission System Operators for Electricity', 'en', 'Rețeaua europeană a operatorilor de transport și de sistem pentru energie electrică', None),
    'RTDSM': ('Real-Time Data Set for Macroeconomists (Philadelphia Fed)', 'en', 'setul de date în timp real pentru macroeconomiști (Philadelphia Fed)', None),
    'QLIKE': ('Quasi-LIKElihood loss', 'en', 'pierderea de tip cvasi-verosimilitate', None),
    'LR': ('Likelihood Ratio (test)', 'en', 'testul raportului de verosimilitate', None),
    'GARCH-N': ('GARCH with Normal innovations', 'en', 'GARCH cu inovații din distribuția Normală', None),
    'HLN': ('Harvey–Leybourne–Newbold (small-sample correction of the DM test)', 'en', 'corecția Harvey–Leybourne–Newbold a testului DM pentru eșantioane mici', None),
    'MSPE': ('Mean Squared Prediction Error', 'en', 'eroarea medie pătratică de prognoză', None),
    'UIP': ('Uncovered Interest Parity', 'en', 'paritatea neacoperită a dobînzilor', None),
    'RW': ('Random Walk', 'en', 'mers aleator', None),
    'CW': ('Clark–West (test for nested models)', 'en', 'testul Clark–West pentru modele imbricate', None),
    'PC': ('Phillips Curve', 'en', 'curba Phillips', None),
    'AO': ('Atkeson–Ohanian (naive inflation forecast)', 'en', 'prognoza naivă a inflației Atkeson–Ohanian', None),
    'ARX': ('AutoRegressive model with eXogenous variables', 'en', 'model autoregresiv cu variabile exogene', None),
    'MW': ('MegaWatt', 'en', 'megawatt', None),
    'SPA': ('Superior Predictive Ability (test)', 'en', 'testul de capacitate predictivă superioară', None),
    'LinEx': ('Linear-Exponential (loss)', 'en', 'pierderea liniar-exponențială', None),
    'GEFCom': ('Global Energy Forecasting Competition', 'en', 'competiția globală de prognoză în energie', None),
    'StepM': ('Stepwise Multiple testing (Romano–Wolf)', 'en', 'testarea multiplă în pași Romano–Wolf', None),
    'LS': ('Log Score', 'en', 'scorul logaritmic', None),
    'IS': ('Interval Score', 'en', 'scorul de interval', None),
    'SE': ('Standard Error; Squared Error', 'en', 'eroare standard; eroare pătratică', None),
    'SCA': ('Seasonally and Calendar Adjusted', 'en', 'ajustat sezonier și după numărul de zile lucrătoare', None),
    'COVID': ('COronaVIrus Disease (2019 pandemic)', 'en', 'boala provocată de coronavirus (pandemia din 2019)', None),
    'UNEMP4': ('SPF variable: unemployment rate forecast for the quarter two quarters after the survey', 'en', 'variabila SPF: prognoza ratei șomajului pentru trimestrul de la două trimestre după anchetă', None),
    'pp': ('percentage points', 'en', 'puncte procentuale', None),
}
OVERRIDE_CH = {
    'SPF': ('Survey of Professional Forecasters (Federal Reserve Bank of Philadelphia)', 'en', 'ancheta trimestrială a prognozatorilor profesioniști (Federal Reserve Bank of Philadelphia)', None),
}
