# Acronime specifice Capitolului 13 ATS (Foundation models și predicție conformală)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
EXTRA = {
    'WQL': ('Weighted Quantile Loss', 'en', 'pierderea cuantilică ponderată', None),
    'CQR': ('Conformalized Quantile Regression', 'en', 'regresia cuantilică conformalizată', None),
    'PID': ('Proportional--Integral--Derivative (controller)', 'en', 'controler proporțional--integral--derivat', None),
    'EnbPI': ('Ensemble batch Prediction Intervals', 'en', 'intervale de predicție din ansambluri bootstrap', None),
    'DtACI': ('Dynamically-tuned Adaptive Conformal Inference', 'en', 'inferența conformală adaptivă cu pas ajustat dinamic', None),
    'AgACI': ('Aggregated Adaptive Conformal Inference', 'en', 'inferența conformală adaptivă agregată', None),
    'CPU': ('Central Processing Unit', 'en', 'procesor central', None),
    'GPU': ('Graphics Processing Unit', 'en', 'procesor grafic', None),
    'T5': ('Text-to-Text Transfer Transformer', 'en', 'Transformer de tip text-la-text (Google)', None),
    'LoRA': ('Low-Rank Adaptation', 'en', 'adaptare de rang redus a ponderilor', None),
    'RLHF': ('Reinforcement Learning from Human Feedback', 'en', 'învățare prin recompensă din evaluări umane', None),
    'OOD': ('Out Of Distribution', 'en', 'în afara distribuției de antrenare', None),
    'CPM': ('Contiguous Patch Masking', 'en', 'mascarea patch-urilor contigue', None),
    'LOTSA': ('Large-scale Open Time Series Archive', 'en', 'arhiva deschisă de serii de timp de mari dimensiuni (Moirai)', None),
    'BOOM': ('Benchmark Of Observability Metrics', 'en', 'benchmark de metrici de observabilitate (Toto)', None),
    'MOMENT': ('MOMENT, a family of open time-series foundation models', 'en', 'familie de foundation models deschise pentru serii de timp', None),
    'GIFT': ('General Time Series Forecasting Model Evaluation (the GIFT-Eval benchmark)', 'en', 'benchmark general pentru evaluarea modelelor de prognoză', None),
    'TS': ('Time Series (in TS-Arena)', 'en', 'serii de timp (în numele TS-Arena)', None),
    'GPT4TS': ('GPT for Time Series (One Fits All)', 'en', 'GPT pentru serii de timp (One Fits All)', None),
    'GPT-2': ('Generative Pre-trained Transformer 2 (OpenAI language model)', 'en', 'model de limbaj al OpenAI, a doua generație', None),
    'ID': ('Identifier (arXiv or DOI)', 'en', 'identificator (arXiv sau DOI)', None),
    'xLSTM': ('extended Long Short-Term Memory', 'en', 'LSTM extins (porți exponențiale, memorie matriceală)', None),
    'NVIDIA': ('NVIDIA Corporation (US company)', 'en', 'NVIDIA Corporation (companie americană)', None),
    'TV': ('Total Variation (distance)', 'en', 'distanța în variație totală', None),
    'ENTSO-E': ('European Network of Transmission System Operators for Electricity', 'en', 'Rețeaua europeană a operatorilor de transport și sistem pentru energie electrică', None),
    'TVA': ('Taxa pe valoarea adăugată', 'ro', None, 'value added tax'),
    'VAT': ('Value Added Tax', 'en', 'taxa pe valoarea adăugată', None),
    'UE': ('Uniunea Europeană', 'ro', None, 'European Union'),
    'CC': ('Creative Commons (licence)', 'en', 'licență Creative Commons', None),
    'MFO': ('Mathematisches Forschungsinstitut Oberwolfach', 'de', 'Institutul de cercetări matematice Oberwolfach', 'Oberwolfach Research Institute for Mathematics'),
}
