# Acronime specifice Capitolului 2 ATS (Rupturi structurale și modele neliniare)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
EXTRA = {
    'CUSUM': ('CUmulative SUM (of recursive residuals)', 'en', 'suma cumulată (a reziduurilor recursive)', None),
    'OLS-CUSUM': ('CUSUM of OLS residuals', 'en', 'CUSUM al reziduurilor OLS', None),
    'MOSUM': ('MOving SUM (of residuals)', 'en', 'suma mobilă (a reziduurilor)', None),
    'CSW': ('Chu, Stinchcombe and White (monitoring boundary)', 'en', 'Chu, Stinchcombe și White (frontiera de monitorizare)', None),
    'ICSS': ('Iterated Cumulative Sums of Squares', 'en', 'sume cumulate de pătrate iterate', None),
    'TAR': ('Threshold AutoRegression', 'en', 'autoregresie cu prag', None),
    'SETAR': ('Self-Exciting Threshold AutoRegression', 'en', 'autoregresie cu prag autoexcitată', None),
    'STAR': ('Smooth Transition AutoRegression', 'en', 'autoregresie cu tranziție netedă', None),
    'LSTAR': ('Logistic Smooth Transition AutoRegression', 'en', 'autoregresie cu tranziție netedă logistică', None),
    'ESTAR': ('Exponential Smooth Transition AutoRegression', 'en', 'autoregresie cu tranziție netedă exponențială', None),
    'JAE': ('Journal of Applied Econometrics', 'en', 'Journal of Applied Econometrics (revistă)', None),
    'BLS': ('Bureau of Labor Statistics (US)', 'en', 'Biroul de statistică a muncii (SUA)', None),
    'OECD': ('Organisation for Economic Co-operation and Development', 'en', 'Organizația pentru Cooperare și Dezvoltare Economică', None),
    'ONS': ('Office for National Statistics (UK)', 'en', 'Oficiul național de statistică (Regatul Unit)', None),
    'UK': ('United Kingdom', 'en', 'Regatul Unit', None),
    'SSR': ('Sum of Squared Residuals', 'en', 'suma pătratelor reziduurilor', None),
    'MPQ': ('McConnell and Perez-Quiros (2000)', 'en', 'McConnell și Perez-Quiros (2000)', None),
    'LWZ': ('Liu, Wu and Zidek (modified Schwarz criterion)', 'en', 'Liu, Wu și Zidek (criteriul Schwarz modificat)', None),
    'PELT': ('Pruned Exact Linear Time (change-point algorithm)', 'en', 'algoritmul PELT de detectare a punctelor de schimbare', None),
    'MSFE': ('Mean Squared Forecast Error', 'en', 'eroarea medie pătratică de prognoză', None),
    'LM1': ('Lagrange Multiplier linearity test, first-order expansion', 'en', 'testul multiplicatorilor Lagrange pentru liniaritate, dezvoltare de ordinul întîi', None),
    'LM3': ('Lagrange Multiplier linearity test, third-order expansion', 'en', 'testul multiplicatorilor Lagrange pentru liniaritate, dezvoltare de ordinul trei', None),
    'PPP': ('Purchasing Power Parity', 'en', 'paritatea puterii de cumpărare', None),
    'PPC': ('Paritatea puterii de cumpărare', 'ro', None, 'purchasing power parity'),
    'IMF': ('International Monetary Fund', 'en', 'Fondul Monetar Internațional', None),
    'FMI': ('Fondul Monetar Internațional', 'ro', None, 'International Monetary Fund'),
    'IFS': ('International Financial Statistics (IMF)', 'en', 'statisticile financiare internaționale (FMI)', None),
    'KSS': ('Kapetanios, Shin and Snell (unit-root test against ESTAR)', 'en', 'testul Kapetanios, Shin și Snell (rădăcină unitară față de ESTAR)', None),
    'FCLT': ('Functional Central Limit Theorem', 'en', 'teorema limită centrală funcțională', None),
    'UDmax': ('Unweighted Double maximum test (Bai–Perron)', 'en', 'testul dublului maxim neponderat (Bai–Perron)', None),
    'WDmax': ('Weighted Double maximum test (Bai–Perron)', 'en', 'testul dublului maxim ponderat (Bai–Perron)', None),
    'AveW': ('Average across estimation Windows (Pesaran–Pick)', 'en', 'media prognozelor peste ferestrele de estimare (Pesaran–Pick)', None),
    'IAPC': ('Indicele armonizat al prețurilor de consum', 'ro', None, 'harmonised index of consumer prices'),
    'HICP': ('Harmonised Index of Consumer Prices', 'en', 'indicele armonizat al prețurilor de consum', None),
    'BDS': ('Brock–Dechert–Scheinkman (test of independence)', 'en', 'testul de independență Brock–Dechert–Scheinkman', None),
    'NLS': ('Nonlinear Least Squares', 'en', 'cele mai mici pătrate neliniare', None),
    'ROBOR': ('Romanian Interbank Offer Rate', 'en', 'rata dobînzii interbancare la care se oferă depozite în lei', None),
    'IT': ('Inclán–Tiao (statistic of the ICSS algorithm)', 'en', 'statistica Inclán–Tiao (din algoritmul ICSS)', None),
    'DF': ('Dickey–Fuller (test)', 'en', 'testul Dickey–Fuller', None),
}
OVERRIDE_CH = {
    'LS': ('Least Squares', 'en', 'cele mai mici pătrate', None),
}
