# Acronime specifice Capitolului 5 ATS (Modele VAR bayesiene, modele factoriale și nowcasting)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
EXTRA = {
    'BVAR': ('Bayesian Vector AutoRegression', 'en', 'model vector autoregresiv bayesian', None),
    'MCMC': ('Markov Chain Monte Carlo', 'en', 'metode Monte Carlo cu lanțuri Markov', None),
    'ESS': ('Effective Sample Size', 'en', 'mărimea efectivă a eșantionului', None),
    'NIW': ('Normal–inverse-Wishart (prior)', 'en', 'distribuția a priori Normal–inverse-Wishart', None),
    'IW': ('inverse Wishart (distribution)', 'en', 'distribuția inverse Wishart', None),
    'IG': ('inverse gamma (distribution)', 'en', 'distribuția inverse gamma', None),
    'MN': ('matrix Normal (distribution)', 'en', 'distribuția Normală matriceală', None),
    'GLP': ('Giannone–Lenza–Primiceri (hierarchical prior selection, 2015)', 'en', 'alegerea ierarhică a distribuției a priori Giannone–Lenza–Primiceri (2015)', None),
    'BGR': ('Bańbura–Giannone–Reichlin (large Bayesian VARs, 2010)', 'en', 'modelele VAR bayesiene mari Bańbura–Giannone–Reichlin (2010)', None),
    'BBE': ('Bernanke–Boivin–Eliasz (FAVAR, 2005)', 'en', 'modelul FAVAR Bernanke–Boivin–Eliasz (2005)', None),
    'SMALL': ('the 3-variable system of BGR (employment, CPI, federal funds rate)', 'en', 'sistemul cu 3 variabile din BGR (ocupare, IPC, dobînda federal funds)', None),
    'MEDIUM': ('the 20-variable system of BGR', 'en', 'sistemul cu 20 de variabile din BGR', None),
    'LARGE': ('the large system of BGR (all series observed over the sample)', 'en', 'sistemul mare din BGR (toate seriile observate pe eșantion)', None),
    'EMPL': ('employment (total private payrolls)', 'en', 'ocuparea (salariații din sectorul privat)', None),
    'FFR': ('Federal Funds Rate', 'en', 'dobînda federal funds', None),
    'FAVAR': ('Factor-Augmented Vector AutoRegression', 'en', 'model VAR augmentat cu factori', None),
    'DFM': ('Dynamic Factor Model', 'en', 'model factorial dinamic', None),
    'DI': ('Diffusion Index (forecast)', 'en', 'prognoză cu indici de difuziune', None),
    'DI-AR': ('Diffusion Index forecast with AutoRegressive lags', 'en', 'prognoză cu indici de difuziune și decalaje autoregresive', None),
    'MIDAS': ('MIxed DAta Sampling (regression)', 'en', 'regresie cu date de frecvențe mixte', None),
    'ADL-MIDAS': ('Autoregressive Distributed Lag MIDAS', 'en', 'regresie MIDAS cu decalaje autoregresive și distribuite', None),
    'U-MIDAS': ('Unrestricted MIDAS', 'en', 'regresie MIDAS nerestricționată', None),
    'EM': ('Expectation–Maximisation (algorithm)', 'en', 'algoritmul expectație–maximizare', None),
    'FRED-MD': ('FRED Monthly Database for macroeconomic research (McCracken–Ng)', 'en', 'baza de date lunară FRED pentru cercetare macroeconomică (McCracken–Ng)', None),
    'NBER': ('National Bureau of Economic Research', 'en', 'Biroul Național de Cercetări Economice al SUA', None),
    'USREC': ('NBER recession indicator (FRED series code)', 'en', 'indicatorul recesiunilor NBER (codul seriei în FRED)', None),
    'CUMFNS': ('Capacity utilisation, manufacturing (FRED series code)', 'en', 'gradul de utilizare a capacităților în industria prelucrătoare (codul seriei în FRED)', None),
    'ESI': ('Economic Sentiment Indicator (European Commission)', 'en', 'indicatorul sentimentului economic (Comisia Europeană)', None),
    'MSFE': ('Mean Squared Forecast Error', 'en', 'eroarea medie pătratică de prognoză', None),
    'NLS': ('Nonlinear Least Squares', 'en', 'metoda celor mai mici pătrate neliniare', None),
    'QML': ('Quasi-Maximum Likelihood', 'en', 'verosimilitate cvasi-maximă', None),
    'SV': ('Stochastic Volatility', 'en', 'volatilitate stochastică', None),
    'INS': ('Institutul Național de Statistică', 'ro', None, 'National Institute of Statistics of Romania'),
    'RW': ('Random Walk', 'en', 'mers aleator', None),
}
