# Acronime specifice Capitolului 6 ATS (Modele în spațiul stărilor și filtrare bayesiană)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
EXTRA = {
    'UC': ('Unobserved Components (model)', 'en', 'model cu componente neobservate', None),
    'UC0': ('UC model with uncorrelated trend and cycle shocks (Clark 1987)', 'en', 'model UC cu șocuri necorelate ale trendului și ciclului (Clark 1987)', None),
    'UC-UR': ('UC model with correlated trend and cycle shocks (Morley–Nelson–Zivot 2003)', 'en', 'model UC cu șocuri corelate ale trendului și ciclului (Morley–Nelson–Zivot 2003)', None),
    'UC-SV': ('Unobserved Components model with Stochastic Volatility (Stock–Watson 2007)', 'en', 'model cu componente neobservate și volatilitate stochastică (Stock–Watson 2007)', None),
    'MNZ': ('Morley–Nelson–Zivot (2003)', 'en', 'Morley–Nelson–Zivot (2003)', None),
    'KSC': ('Kim–Shephard–Chib (1998), mixture sampler for stochastic volatility', 'en', 'Kim–Shephard–Chib (1998), eșantionatorul cu mixtură pentru volatilitatea stochastică', None),
    'PMMH': ('Particle Marginal Metropolis–Hastings', 'en', 'algoritmul Metropolis–Hastings marginal cu filtru de particule', None),
    'TVP': ('Time-Varying Parameter(s)', 'en', 'parametri variabili în timp', None),
    'TVP-VAR': ('Time-Varying-Parameter Vector AutoRegression', 'en', 'model VAR cu parametri variabili în timp', None),
    'TVP-VAR-SV': ('TVP-VAR with Stochastic Volatility', 'en', 'model VAR cu parametri variabili în timp și volatilitate stochastică', None),
    'FFBS': ('Forward Filtering, Backward Sampling', 'en', 'filtrare înainte, eșantionare înapoi', None),
    'DK': ('Durbin–Koopman (simulation smoother, 2002)', 'en', 'algoritmul Durbin–Koopman (2002) de simulare a stărilor netezite', None),
    'EKF': ('Extended Kalman Filter', 'en', 'filtrul Kalman extins', None),
    'UKF': ('Unscented Kalman Filter', 'en', 'filtrul Kalman unscented', None),
    'APF': ('Auxiliary Particle Filter', 'en', 'filtrul de particule auxiliar', None),
    'SMC': ('Sequential Monte Carlo', 'en', 'metode Monte Carlo secvențiale', None),
    'DSGE': ('Dynamic Stochastic General Equilibrium (model)', 'en', 'model dinamic stochastic de echilibru general', None),
    'BN': ('Beveridge–Nelson (decomposition)', 'en', 'descompunerea Beveridge–Nelson', None),
    'IMA': ('Integrated Moving Average (model)', 'en', 'model integrat de medie mobilă', None),
    'BSTS': ('Bayesian Structural Time Series', 'en', 'serii de timp structurale bayesiene', None),
    'FERMIAC': ('mechanical Monte Carlo device of Enrico Fermi (Los Alamos, 1947)', 'en', 'dispozitiv mecanic Monte Carlo al lui Enrico Fermi (Los Alamos, 1947)', None),
}
