# Acronime specifice Capitolului 8 ATS (Modelarea avansată a volatilității: măsuri realizate, HAR și GARCH multivariat)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
EXTRA = {
    'QML': ('Quasi-Maximum Likelihood', 'en', 'verosimilitate cvasi-maximă', None),
    'QMLE': ('Quasi-Maximum Likelihood Estimator', 'en', 'estimatorul de verosimilitate cvasi-maximă', None),
    'OPG': ('Outer Product of the Gradient (scores)', 'en', 'produsul exterior al scorurilor', None),
    'IGARCH': ('Integrated GARCH', 'en', 'GARCH integrat', None),
    'GARCH-X': ('GARCH with eXogenous variables', 'en', 'GARCH cu variabile exogene', None),
    'MIDAS': ('MIxed DAta Sampling', 'en', 'regresie cu date de frecvențe mixte', None),
    'GARCH-MIDAS': ('GARCH with a MIxed DAta Sampling long-run component (Engle–Ghysels–Sohn 2013)', 'en', 'GARCH cu o componentă de termen lung MIDAS (Engle–Ghysels–Sohn 2013)', None),
    'RV': ('Realised Variance', 'en', 'varianța realizată', None),
    'BV': ('Bipower Variation', 'en', 'variația bipower', None),
    'RK': ('Realised Kernel', 'en', 'estimator cu nucleu al varianței integrate, robust la zgomotul de microstructură', None),
    'IV': ('Integrated Variance', 'en', 'varianța integrată', None),
    'QV': ('Quadratic Variation', 'en', 'variația pătratică', None),
    'IQ': ('Integrated Quarticity', 'en', 'cuarticitatea integrată', None),
    'RQ': ('Realised Quarticity', 'en', 'cuarticitatea realizată', None),
    'TQ': ('Tripower Quarticity', 'en', 'cuarticitatea tripower', None),
    'TSRV': ('Two-Scales Realised Variance', 'en', 'varianța realizată cu două scale de timp', None),
    'MedRV': ('Median Realised Variance', 'en', 'varianța realizată mediană', None),
    'MinRV': ('Minimum Realised Variance', 'en', 'varianța realizată minimă', None),
    'RCov': ('Realised Covariance', 'en', 'covarianța realizată', None),
    'RM': ('Realised Measure', 'en', 'măsură realizată', None),
    'HAR-CJ': ('HAR with Continuous and Jump components', 'en', 'HAR cu componente continuă și de salt', None),
    'HARQ': ('HAR with realised Quarticity', 'en', 'HAR cu cuarticitatea realizată', None),
    'HEAVY': ('High-frEquency-bAsed VolatilitY (models)', 'en', 'modele de volatilitate pe baza datelor de înaltă frecvență', None),
    'RGARCH': ('Realized GARCH', 'en', 'model GARCH cu măsură realizată', None),
    'BEKK': ('Baba–Engle–Kraft–Kroner (multivariate GARCH)', 'en', 'GARCH multivariat Baba–Engle–Kraft–Kroner', None),
    'VEC': ('VEC multivariate GARCH (half-vectorised covariance)', 'en', 'GARCH multivariat VEC (covarianța semivectorizată)', None),
    'CCC': ('Constant Conditional Correlation', 'en', 'corelație condiționată constantă', None),
    'cDCC': ('corrected Dynamic Conditional Correlation (Aielli 2013)', 'en', 'corelație condiționată dinamică corectată (Aielli 2013)', None),
    'DCC-NL': ('DCC with Nonlinear shrinkage of the target (Engle–Ledoit–Wolf 2019)', 'en', 'DCC cu shrinkage neliniar al țintei (Engle–Ledoit–Wolf 2019)', None),
    'NL': ('NonLinear (shrinkage)', 'en', 'neliniar (shrinkage)', None),
    'LW': ('Ledoit–Wolf (shrinkage)', 'en', 'shrinkage Ledoit–Wolf', None),
    'GMV': ('Global Minimum-Variance (portfolio)', 'en', 'portofoliul de varianță minimă globală', None),
    'BNHLS': ('Barndorff-Nielsen–Hansen–Lunde–Shephard', 'en', 'Barndorff-Nielsen–Hansen–Lunde–Shephard', None),
    'BNS': ('Barndorff-Nielsen–Shephard', 'en', 'Barndorff-Nielsen–Shephard', None),
    'OMI': ('Oxford-Man Institute (of Quantitative Finance)', 'en', 'Institutul Oxford-Man de finanțe cantitative', None),
    'PPI': ('Producer Price Index', 'en', 'indicele prețurilor producției (IPP)', None),
    'IPP': ('Indicele Prețurilor Producției', 'ro', None, 'producer price index'),
    'MSE': ('Mean Squared Error', 'en', 'eroarea pătratică medie', None),
    'MAE': ('Mean Absolute Error', 'en', 'eroarea absolută medie', None),
    'CAC': ('Cotation Assistée en Continu (CAC 40 index, Paris)', 'fr', 'indicele CAC 40 al bursei din Paris', 'the CAC 40 index of the Paris bourse'),
    'CDS': ('Credit Default Swap', 'en', 'contract swap pe riscul de nerambursare', None),
    'FTX': ('FTX (cryptocurrency exchange, bankrupt in November 2022)', 'en', 'FTX (bursă de criptomonede, intrată în faliment în noiembrie 2022)', None),
    'MSTR': ('MicroStrategy (Strategy Inc.), NASDAQ ticker', 'en', 'MicroStrategy (Strategy Inc.), simbolul bursier NASDAQ', None),
    'TSLA': ('Tesla Inc., NASDAQ ticker', 'en', 'Tesla Inc., simbolul bursier NASDAQ', None),
    'UTC': ('Coordinated Universal Time', 'en', 'timpul universal coordonat', None),
}
