# Acronime specifice Capitolului 9 ATS (VaR, ES și backtesting: elicitabilitate, funcții de scor și riscul de model)
# format: acronim -> (forma de origine, limba de origine, traducere RO, traducere EN)
# OVERRIDE_CH: acronim -> tuplu, sens diferit doar in acest capitol (EM, IG, RQ, QR au alt sens in alte capitole).
EXTRA = {
    'FZ': ('Fissler–Ziegel (class of scoring functions for VaR and ES)', 'en', 'clasa Fissler–Ziegel de funcții de scor pentru VaR și ES', None),
    'FZ0': ('Zero-homogeneous Fissler–Ziegel loss (Patton, Ziegel and Chen)', 'en', 'pierderea Fissler–Ziegel omogenă de grad zero (Patton, Ziegel și Chen)', None),
    'DQ': ('Dynamic Quantile (test of Engle and Manganelli)', 'en', 'testul dinamic pe cuantile al lui Engle și Manganelli', None),
    'GAS': ('Generalised Autoregressive Score (model)', 'en', 'model autoregresiv determinat de scor', None),
    'GAS-FZ': ('GAS models for VaR and ES driven by the FZ0 loss', 'en', 'modele GAS pentru VaR și ES determinate de pierderea FZ0', None),
    'GAS-1F': ('One-factor GAS model for VaR and ES', 'en', 'model GAS cu un factor pentru VaR și ES', None),
    'GAS-2F': ('Two-factor GAS model for VaR and ES', 'en', 'model GAS cu doi factori pentru VaR și ES', None),
    'FZ-1F': ('One-factor GAS model for VaR and ES (label of Patton, Ziegel and Chen)', 'en', 'model GAS cu un factor pentru VaR și ES (eticheta lui Patton, Ziegel și Chen)', None),
    'FZ-2F': ('Two-factor GAS model for VaR and ES (label of Patton, Ziegel and Chen)', 'en', 'model GAS cu doi factori pentru VaR și ES (eticheta lui Patton, Ziegel și Chen)', None),
    'GARCH-FZ': ('GARCH model estimated by FZ0 minimisation', 'en', 'model GARCH estimat prin minimizarea pierderii FZ0', None),
    'GCH': ('GARCH (short label in tables)', 'en', 'GARCH (etichetă scurtă în tabele)', None),
    'GCH-N': ('ARMA-GARCH with Normal innovations', 'en', 'ARMA-GARCH cu inovații din distribuția Normală', None),
    'GCH-EDF': ('ARMA-GARCH with innovations from the empirical distribution function', 'en', 'ARMA-GARCH cu inovații din funcția de repartiție empirică', None),
    'GCH-FZ': ('GARCH model estimated by FZ0 minimisation (table label)', 'en', 'model GARCH estimat prin minimizarea pierderii FZ0 (etichetă de tabel)', None),
    'GARCH-EDF': ('GARCH with innovations from the empirical distribution function', 'en', 'GARCH cu inovații din funcția de repartiție empirică', None),
    'ARMA-GARCH': ('ARMA mean with GARCH variance', 'en', 'medie ARMA cu varianță GARCH', None),
    'EDF': ('Empirical Distribution Function', 'en', 'funcția de repartiție empirică', None),
    'RW-125': ('Rolling Window of 125 days (historical simulation)', 'en', 'fereastră mobilă de 125 de zile (simulare istorică)', None),
    'RW-250': ('Rolling Window of 250 days (historical simulation)', 'en', 'fereastră mobilă de 250 de zile (simulare istorică)', None),
    'RW-500': ('Rolling Window of 500 days (historical simulation)', 'en', 'fereastră mobilă de 500 de zile (simulare istorică)', None),
    'HS': ('Historical Simulation', 'en', 'simulare istorică', None),
    'FHS': ('Filtered Historical Simulation', 'en', 'simulare istorică filtrată', None),
    'EVT': ('Extreme Value Theory', 'en', 'teoria valorilor extreme', None),
    'GPL': ('Generalised Piecewise Linear (scoring function)', 'en', 'funcție de scor liniară pe porțiuni generalizată', None),
    'PZC': ('Patton, Ziegel and Chen (2019)', 'en', 'Patton, Ziegel și Chen (2019)', None),
    'SAV': ('Symmetric Absolute Value (CAViaR specification)', 'en', 'specificația CAViaR cu valoare absolută simetrică', None),
    'AS': ('Asymmetric Slope (CAViaR specification)', 'en', 'specificația CAViaR cu pantă asimetrică', None),
    'ADAPT': ('Adaptive (CAViaR specification)', 'en', 'specificația CAViaR adaptivă', None),
    'GM': ('General Motors (stock)', 'en', 'acțiunea General Motors', None),
    'IBM': ('International Business Machines (stock)', 'en', 'acțiunea International Business Machines', None),
    'FRTB': ('Fundamental Review of the Trading Book (Basel)', 'en', 'revizuirea fundamentală a portofoliului de tranzacționare (Basel)', None),
    'MAR33': ('Basel Framework, chapter MAR33 (internal models, capital requirements)', 'en', 'Cadrul Basel, capitolul MAR33 (modele interne, cerințe de capital)', None),
    'HC0': ('Heteroskedasticity-Consistent covariance of White (type 0)', 'en', 'covarianța White robustă la heteroscedasticitate (tipul 0)', None),
    'GJR': ('Glosten–Jagannathan–Runkle (asymmetric GARCH)', 'en', 'modelul GARCH asimetric Glosten–Jagannathan–Runkle', None),
    'ACI': ('Adaptive Conformal Inference', 'en', 'inferență conformală adaptivă', None),
}
OVERRIDE_CH = {
    'EM': ('Engle and Manganelli (2004), CAViaR', 'en', 'Engle și Manganelli (2004), CAViaR', None),
    'IG': ('Indirect GARCH (CAViaR specification)', 'en', 'specificația CAViaR GARCH indirect', None),
    'RQ': ('Regression Quantile (criterion of Engle and Manganelli)', 'en', 'criteriul de regresie cuantilică al lui Engle și Manganelli', None),
    'QR': ('Quantile Regression', 'en', 'regresie cuantilică', None),
    'IS': ('In-Sample', 'en', 'în eșantion', None),
}
